# -*- coding: utf-8 -*-
"""CompGraf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CA9nEjl6FdwFh5ATKwzDwXWpE0YMb5g-
"""

import cv2
import imutils
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter
from sys import argv

img = cv2.imread(r"/content/Images/coins3.jpg")

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

binr = cv2.threshold(imgray, 245, 255, cv2.THRESH_BINARY)[1]

inv = cv2.bitwise_not(binr)

med = cv2.medianBlur(inv, 3)

cnts = cv2.findContours(med.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

cnts = imutils.grab_contours(cnts)
objects = str(len(cnts))

print ('Objetos encontrados: ', objects)
plt.imshow(med)